{
    "name": "GigaClub Team",
    "version": "16.0.1.0.0",
    "summary": "GigaClub Team Module",
    "category": "GigaClub",
    "author": "GigaClub.net",
    "website": "https://GigaClub.net",
    "license": "AGPL-3",
    "depends": ["gigaclub_requests", "gigaclub_permission_system"],
    "data": [
        "data/gc_permission_group_data.xml",
        "data/gc_permission_model_data.xml",
        "data/gc_permission_model_entry_data.xml",
        "data/gc_permission_profile_data.xml",
        "data/gc_permission_profile_entry_data.xml",
        "data/gc_permission_profile_entry_template_data.xml",
        "data/gc_permission_profile_template_data.xml",
        "security/ir.model.access.csv",
        "views/gc_permission_connector_views.xml",
        "views/gc_team_views.xml",
        "views/menu_views.xml",
    ],
    "installable": True,
    "auto_install": False,
}
