from odoo import fields, models


class GCDiscordPermissionProfile(models.Model):
    _name = "gc.discord.permission.profile"
    _description = "GigaClub Discord Permission Profile"

    name = fields.Char()

    administrator = fields.Boolean()
    create_instant_invite = fields.Boolean()
    kick_members = fields.Boolean()
    ban_members = fields.Boolean()
    manage_channels = fields.Boolean()
    manage_guild = fields.Boolean()
    add_reactions = fields.Boolean()
    view_audit_log = fields.Boolean()
    priority_speaker = fields.Boolean()
    stream = fields.Boolean()
    read_messages = fields.Boolean()
    send_messages = fields.Boolean()
    send_tts_messages = fields.Boolean()
    manage_messages = fields.Boolean()
    embed_links = fields.Boolean()
    attach_files = fields.Boolean()
    read_message_history = fields.Boolean()
    mention_everyone = fields.Boolean()
    external_emojis = fields.Boolean()
    view_guild_insights = fields.Boolean()
    connect = fields.Boolean()
    speak = fields.Boolean()
    mute_members = fields.Boolean()
    deafen_members = fields.Boolean()
    move_members = fields.Boolean()
    use_voice_activation = fields.Boolean()
    change_nickname = fields.Boolean()
    manage_nicknames = fields.Boolean()
    manage_roles = fields.Boolean()
    manage_webhooks = fields.Boolean()
    manage_emojis = fields.Boolean()
    request_to_speak = fields.Boolean()
    view_channel = fields.Boolean()
    use_external_emojis = fields.Boolean()
    manage_permissions = fields.Boolean()
    manage_emojis_and_stickers = fields.Boolean()
    use_application_commands = fields.Boolean()
    manage_events = fields.Boolean()
    manage_threads = fields.Boolean()
    create_public_threads = fields.Boolean()
    create_private_threads = fields.Boolean()
    send_messages_in_threads = fields.Boolean()
    external_stickers = fields.Boolean()
    use_external_stickers = fields.Boolean()
    use_embedded_activities = fields.Boolean()
    moderate_members = fields.Boolean()
