{
    "name": "GigaClub Discord Project",
    "version": "16.0.1.0.0",
    "category": "GigaClub",
    "author": "GigaClub",
    "website": "https://github.com/GigaClub/gigaclub_odoo",
    "license": "AGPL-3",
    "depends": ["gigaclub_discord", "gigaclub_project"],
    "data": [
        "data/base_automation_data.xml",
        "data/gc_discord_category_data.xml",
        "data/gc_discord_channel_data.xml",
        "data/gc_discord_message_template_data.xml",
        "data/gc_discord_embed_template_data.xml",
        "data/gc_discord_embed_field_template_data.xml",
    ],
    "demo": [],
    "installable": True,
    "auto_install": False,
}
