{
    "name": "GigaClub Discord",
    "version": "16.0.1.0.0",
    "summary": "GigaClub Discord Bot Module",
    "category": "GigaClub",
    "author": "GigaClub",
    "website": "https://github.com/GigaClub/gigaclub_odoo",
    "license": "AGPL-3",
    "depends": ["gigaclub_builder_system"],
    "external_dependencies": {"python": ["discord.py"]},
    "data": [
        "data/gc_discord_category_data.xml",
        "data/gc_discord_channel_data.xml",
        "data/gc_discord_permission_profile_data.xml",
        "data/gc_discord_role_data.xml",
        "views/menu_views.xml",
        "views/gc_discord_action_views.xml",
        "views/gc_discord_action_worker_views.xml",
        "views/gc_discord_button_views.xml",
        "views/gc_discord_category_views.xml",
        "views/gc_discord_channel_views.xml",
        "views/gc_discord_embed_field_template_views.xml",
        "views/gc_discord_embed_template_views.xml",
        "views/gc_discord_event_views.xml",
        "views/gc_discord_event_worker_views.xml",
        "views/gc_discord_message_views.xml",
        "views/gc_discord_message_template_views.xml",
        "views/gc_discord_modal_views.xml",
        "views/gc_discord_permission_profile_overwrite_views.xml",
        "views/gc_discord_permission_profile_views.xml",
        "views/gc_discord_role_views.xml",
        "views/gc_discord_select_item_views.xml",
        "views/gc_discord_select_views.xml",
        "views/gc_discord_text_input_views.xml",
        "views/gc_discord_view_views.xml",
        "views/gc_user_views.xml",
        "views/res_config_settings_views.xml",
        "security/ir.model.access.csv",
    ],
    "installable": True,
    "auto_install": False,
}
