{
    "name": "GigaClub Gamification",
    "version": "16.0.1.0.0",
    "category": "GigaClub",
    "author": "GigaClub",
    "website": "https://github.com/GigaClub/gigaclub_odoo",
    "license": "AGPL-3",
    "depends": ["gigaclub_base"],
    "data": [
        "security/ir.model.access.csv",
        "views/menu_views.xml",
        "views/gc_advancement_connector_views.xml",
        "views/gc_advancement_views.xml",
        "views/gc_coins_transaction_views.xml",
        "views/gc_experience_connector_views.xml",
        "views/gc_experience_level_views.xml",
        "views/gc_experience_views.xml",
        "views/gc_reward_connector_views.xml",
        "views/gc_reward_views.xml",
    ],
    "demo": [],
    "installable": True,
    "auto_install": False,
}
