{
    "name": "GigaClub Permission System",
    "version": "16.0.1.0.0",
    "category": "GigaClub",
    "author": "GigaClub.net",
    "website": "https://GigaClub.net",
    "license": "AGPL-3",
    "depends": ["gigaclub_base"],
    "data": [
        "data/gc_permission_group_data.xml",
        "data/gc_permission_model_entry_data.xml",
        "data/gc_permission_profile_entry_template_data.xml",
        "data/gc_permission_profile_template_data.xml",
        "data/gc_permission_profile_data.xml",
        "data/gc_permission_profile_entry_data.xml",
        "security/ir.model.access.csv",
        "views/menu_views.xml",
        "views/gc_permission_connector_views.xml",
        "views/gc_permission_group_views.xml",
        "views/gc_permission_model_entry_views.xml",
        "views/gc_permission_model_views.xml",
        "views/gc_permission_profile_entry_template_views.xml",
        "views/gc_permission_profile_entry_views.xml",
        "views/gc_permission_profile_template_views.xml",
        "views/gc_permission_profile_views.xml",
        "views/gc_user_views.xml",
    ],
    "demo": [],
    "installable": True,
    "auto_install": False,
}
